### ISSUE TITLE
File Existence Problem

### ISSUE THREAD

**Issue by vickydasta** [homina/pica#3]
```
vickydasta@vickydasta:~/.config/gtk-3.0$ ls
bookmarks
vickydasta@vickydasta:~/.config/gtk-3.0$ pica x.jpg

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-backgrounds.css:28:8: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-backgrounds.css:62:8: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-backgrounds.css:79:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-backgrounds.css:89:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-backgrounds.css:132:8: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-backgrounds.css:160:52: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-backgrounds.css:194:21: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:8:8: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:67:16: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:121:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:157:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:188:40: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:231:21: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:249:21: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:272:32: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:301:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-borders.css:313:27: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:69:7: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:77:7: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:111:7: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:118:7: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:136:21: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:150:21: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:33:15: 'outline-radius' is not a valid property name

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:159:25: No property named '-gtk-icon-transform'

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:925:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:934:8: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:949:24: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1025:16: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1064:27: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1082:16: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1096:16: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1111:16: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1126:16: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1140:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1154:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1167:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1180:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1209:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1246:39: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1270:39: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1295:39: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1321:32: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1337:50: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1351:62: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1362:61: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1376:41: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1391:41: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1406:41: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1421:41: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1433:2: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1483:164: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1922:40: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1940:40: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2162:35: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2193:35: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2208:35: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2222:43: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2232:52: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2372:33: 'theme_text_color' is not a valid color name

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2408:12: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2426:13: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2452:12: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2459:12: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2466:13: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2478:12: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2493:12: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2502:12: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2525:12: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2720:34: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2741:34: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2752:25: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2783:27: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2799:27: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2865:35: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2880:35: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2888:35: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2932:52: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2948:52: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2956:52: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2994:50: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3005:50: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3270:21: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3308:26: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3321:12: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3494:14: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3593:21: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3609:22: Missing name of pseudo-class

(main.py:15226): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3627:22: Missing name of pseudo-class

(main.py:15226): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
Traceback (most recent call last):
  File "/usr/share/pica/main.py", line 700, in on_button_clicked
    self.fit_screen()
  File "/usr/share/pica/main.py", line 631, in fit_screen
    self.load_buffer_image()
  File "/usr/share/pica/main.py", line 501, in load_buffer_image
    self.ori_image = GdkPixbuf.Pixbuf.new_from_file(self.current_image)
gi._glib.GError: Failed to open file 'x.jpg': No such file or directory
Traceback (most recent call last):
  File "/usr/share/pica/main.py", line 700, in on_button_clicked
    self.fit_screen()
  File "/usr/share/pica/main.py", line 631, in fit_screen
    self.load_buffer_image()
  File "/usr/share/pica/main.py", line 501, in load_buffer_image
    self.ori_image = GdkPixbuf.Pixbuf.new_from_file(self.current_image)
gi._glib.GError: Failed to open file 'x.jpg': No such file or directory

```
It would be nicer if there's a function to check wether the file is exist or not,
and if the file is not exist,some error message,i mean a more user friendly error message will be appear.

**Comment by homina** [comment]
thank you for the suggestion, i will try to fix it for the next release.
